// =============================================================================
// Citations registry.
//
// Every parameter that meaningfully affects the model points to an entry here.
// Each entry carries a `confidence` field marking it as one of:
//   - 'sourced'      Directly verified against the cited publication.
//   - 'extrapolated' Sourced reasoning applied to a derived calculation,
//                    or a number consistent with the cited source but not
//                    directly verified.
//   - 'judgement'    Designer judgement with documented reasoning.
//
// Coverage rule: every numeric constant in params.js, every reform's numeric
// effect, every event probability base, and every risk-modifier coefficient
// must point to an entry here. Use { value, citationId } at the leaf in the
// data modules; the engine reads `.value` and the UI reads `.citationId`.
//
// Citation IDs follow `source_topic_specific` format:
//   hmrc_basic_rate, ifs_cgt_alignment, marmot_austerity_mortality.
// =============================================================================

export const CONFIDENCE = {
  SOURCED: 'sourced',
  EXTRAPOLATED: 'extrapolated',
  JUDGEMENT: 'judgement',
};

export const CITATIONS = {
  // ===========================================================================
  // Cross-cutting methodology notes (referenced by many parameters)
  // ===========================================================================
  bloc_methodology: {
    parameter: 'ALL bloc reactions to policy',
    confidence: 'judgement',
    title: 'Bloc-reaction methodology',
    note: "Bloc reactions to policy are designer judgements informed by YouGov, Ipsos, and British Election Study polling patterns. They are not estimated from data. Numbers are calibrated to produce plausible coalition dynamics, not to forecast actual public opinion.",
  },
  event_probability_methodology: {
    parameter: 'ALL event base probabilities',
    confidence: 'judgement',
    title: 'Event-probability methodology',
    note: 'Event base probabilities are designer-set to produce plausible quarterly risk patterns. They are modified by reasonable mechanisms (NHS pay deal cuts strike risk; deregulation raises financial-crisis risk). Magnitudes are calibrated, not estimated.',
  },
  forecast_noise_methodology: {
    parameter: 'forecastNoise (±25% / ±10%)',
    confidence: 'judgement',
    title: 'Forecast-uncertainty methodology',
    note: 'The ±25% noise band on reform outcomes (reduced to ±10% after passing OBR Independence) is a designer judgement representing genuine UK fiscal forecasting uncertainty. Magnitudes loosely calibrated to OBR forecast-error ranges but not formally derived.',
  },

  // ===========================================================================
  // Revenue baselines (HMRC Ready Reckoner / receipts)
  // ===========================================================================
  hmrc_ready_reckoner: {
    parameter: 'income tax / NI / VAT / corp-tax per-pp revenue figures',
    confidence: 'sourced',
    title: 'Direct effects of illustrative tax changes bulletin (June 2025)',
    publisher: 'HMRC',
    year: 2025,
    url: 'https://www.gov.uk/government/statistics/direct-effects-of-illustrative-tax-changes',
    note: 'Authoritative source for per-pp tax rate yields. June 2025 bulletin (updated 24 June 2025), aligned to OBR March 2025 EFO economy forecast, costing measures implemented April 2026 onwards. All sim per-pp yields verified directly against this document on 2026-05-14.',
  },
  hmrc_basic_rate: {
    parameter: 'incomeTax.basicRatePerPP',
    value: 6.9,
    unit: '£bn pa per 1pp',
    confidence: 'sourced',
    title: 'Direct effects of illustrative tax changes — basic rate',
    publisher: 'HMRC',
    year: 2025,
    url: 'https://www.gov.uk/government/statistics/direct-effects-of-illustrative-tax-changes',
    note: 'HMRC June 2025 bulletin §5 (income tax rates): change basic rate by 1p = £6,900m in FY 2026-27 (the simulation\'s starting year). Rises to £8,250m by 2027-28 and £8,200m by 2028-29. Sim uses 2026-27 figure since the player\'s first decisions affect that year. Verified directly against HMRC PDF on 2026-05-14.',
  },
  hmrc_higher_rate: {
    parameter: 'incomeTax.higherRatePerPP',
    value: 1.6,
    unit: '£bn pa per 1pp',
    confidence: 'sourced',
    title: 'Direct effects of illustrative tax changes — higher rate',
    publisher: 'HMRC',
    year: 2025,
    url: 'https://www.gov.uk/government/statistics/direct-effects-of-illustrative-tax-changes',
    note: 'HMRC June 2025 bulletin §5 (income tax rates): change higher rate by 1p = £1,600m in FY 2026-27. Rises to £2,150m / £2,100m in subsequent years. Behavioural responses (taxable income elasticities, tax-motivated incorporations) baked in by HMRC. Verified directly against HMRC PDF on 2026-05-14 — the sourced figure (£1.6bn) replaces the £2bn estimate that was triangulated from Oxford commentary.',
  },
  diamond_saez_top_rate: {
    parameter: 'incomeTax.additionalRatePerPP',
    value: 0.16,
    unit: '£bn pa per 1pp at additional rate',
    confidence: 'sourced',
    title: 'HMRC additional-rate yield + Diamond-Saez context',
    publisher: 'HMRC; Diamond & Saez (2011)',
    authors: ['Peter Diamond', 'Emmanuel Saez'],
    year: 2025,
    url: 'https://www.gov.uk/government/statistics/direct-effects-of-illustrative-tax-changes',
    note: 'HMRC June 2025 bulletin §5 publishes asymmetric values for FY 2026-27: increase 1p = £145m yield, decrease 1p = £175m cost (the Laffer-curve gap reflects taxable-income elasticities at the top of the distribution). Sim uses the £160m midpoint as its single per-pp coefficient. Includes carried-interest impacts (carried interest moves into income tax framework from April 2026 per Autumn Budget 2024). Diamond-Saez (2011) revenue-maximising top combined rate ~73% (ETI=0.25) remains the upstream theory. Verified directly against HMRC PDF on 2026-05-14 — sourced value replaces the £0.9bn designer override flagged in the prior audit.',
  },
  hmrc_corp_rate: {
    parameter: 'corpTax.perPP',
    value: 3.6,
    unit: '£bn pa per 1pp',
    confidence: 'sourced',
    title: 'Direct effects of illustrative tax changes — corporation tax',
    publisher: 'HMRC',
    year: 2025,
    url: 'https://www.gov.uk/government/statistics/direct-effects-of-illustrative-tax-changes',
    note: 'HMRC June 2025 bulletin §12: change main + small profits onshore CT rate by 1pp = £3,600m in FY 2026-27 (rising to £3,900m / £4,000m in 2027-28 / 2028-29). Excludes offshore CT, Energy Profits Levy, Bank Surcharge, Residential Property Developer Tax. Time-adjusted cash basis matching ONS PSF treatment. Verified directly against HMRC PDF on 2026-05-14.',
  },
  corp_elasticity_curve: {
    parameter: 'corpTax.curvatureAbove30',
    value: 0.5,
    unit: 'quadratic penalty coefficient',
    confidence: 'judgement',
    title: 'Corp-tax behavioural-response curvature',
    note: 'Above ~30% headline rate, marginal revenue declines through profit-shifting and avoidance. The quadratic penalty is a designer simplification of behavioural-response literature, not a directly cited elasticity.',
  },
  policy_threshold_judgement: {
    parameter: 'policy / spending behavioural thresholds',
    confidence: 'judgement',
    title: 'Policy thresholds for bloc & risk responses',
    note: 'Bloc reactions and risk modifiers kick in at designer-set policy thresholds (e.g. corp tax 28% high / 22% low; NHS boost above £210bn; investment-surge boost above £45bn infra). These thresholds are judgement-set to match the simulation\'s game-balance intent, not derived from data.',
  },
  hmrc_vat_rate: {
    parameter: 'vat.perPP',
    value: 8.8,
    unit: '£bn pa per 1pp',
    confidence: 'sourced',
    title: 'Direct effects of illustrative tax changes — VAT standard rate',
    publisher: 'HMRC',
    year: 2025,
    url: 'https://www.gov.uk/government/statistics/direct-effects-of-illustrative-tax-changes',
    note: 'HMRC June 2025 bulletin §18: change VAT standard rate by 1pp = £8,800m in FY 2026-27 (rising to £9,200m / £9,550m). Reduced rate per-pp impact is £490m. Verified directly against HMRC PDF on 2026-05-14 — replaces the £8.5bn estimate uprated from older Treasury Committee anchor.',
  },
  hmrc_baseline_income_tax: {
    parameter: 'incomeTax.base',
    value: 330,
    unit: '£bn pa (baseline receipts)',
    confidence: 'sourced',
    title: 'UK income tax receipts 2025-26',
    publisher: 'HMRC / OBR EFO Nov 2025',
    year: 2025,
    url: 'https://obr.uk/efo/economic-and-fiscal-outlook-november-2025/',
    note: 'OBR Nov-2025 EFO / HMRC: income tax forecast £330bn in 2025-26 (up from £302.7bn outturn in 2024-25). Combined with NICs £205bn the total IT+NIC is £535bn per the OBR brief guide.',
  },
  hmrc_baseline_corp: {
    parameter: 'corpTax.base',
    value: 96,
    unit: '£bn pa (baseline receipts)',
    confidence: 'sourced',
    title: 'UK onshore corporation tax receipts 2025-26',
    publisher: 'OBR Brief Guide',
    year: 2025,
    url: 'https://obr.uk/forecasts-in-depth/brief-guides-and-explainers/public-finances/',
    note: 'OBR brief guide: onshore CT forecast £95.8bn in 2025-26 (~7.9% of receipts). Rounded to £96bn.',
  },
  hmrc_baseline_vat: {
    parameter: 'vat.base',
    value: 181,
    unit: '£bn pa (baseline receipts)',
    confidence: 'sourced',
    title: 'UK VAT receipts 2025-26',
    publisher: 'OBR Brief Guide',
    year: 2025,
    url: 'https://obr.uk/forecasts-in-depth/tax-by-tax-spend-by-spend/vat/',
    note: 'OBR brief guide: VAT forecast £181bn in 2025-26. Per-pp yield held at £8.5bn (sourced separately).',
  },
  hmrc_baseline_ni: {
    parameter: 'ni',
    value: 205,
    unit: '£bn pa (baseline receipts)',
    confidence: 'sourced',
    title: 'UK National Insurance receipts 2025-26',
    publisher: 'OBR EFO Nov 2025',
    year: 2025,
    url: 'https://obr.uk/forecasts-in-depth/tax-by-tax-spend-by-spend/national-insurance-contributions-nics/',
    note: 'OBR Nov-2025 EFO: NICs forecast £205bn in 2025-26 (recovering from £172.5bn 2024-25 outturn after the 2p NIC cut).',
  },
  hmrc_other_baseline: {
    parameter: 'other (residual revenues)',
    value: 423,
    unit: '£bn pa',
    confidence: 'sourced',
    title: 'UK other public-sector receipts (residual) 2025-26',
    publisher: 'OBR Brief Guide / HMRC',
    year: 2025,
    url: 'https://obr.uk/forecasts-in-depth/brief-guides-and-explainers/public-finances/',
    note: 'Residual to reconcile total receipts with OBR Nov-2025 forecast of £1,235bn (= £330 income tax + £205 NICs + £181 VAT + £96 CT + £423 other). Other includes: council tax + business rates + fuel duty (OBR £24bn) + CGT (OBR ~£20bn) + IHT + stamp duty + alcohol/tobacco/excise + insurance premium tax + air passenger duty + public-corp surpluses + other receipts. Per the OBR brief guide, no individual "other" tax exceeds £20bn.',
  },

  // ===========================================================================
  // Spending baselines
  // ===========================================================================
  dwp_state_pensions: {
    parameter: 'fixedCosts.pensions',
    value: 146,
    unit: '£bn pa',
    confidence: 'sourced',
    title: 'UK state pension expenditure (2025-26)',
    publisher: 'DWP / HoC Library CDP-2025-0035',
    year: 2025,
    url: 'https://commonslibrary.parliament.uk/research-briefings/cdp-2025-0035/',
    note: 'State Pension forecast £146.1bn in 2025-26 (pensioner benefits total £177.7bn). Triple-locked; treated as locked AME in the sim. Verified via Commons Library briefing.',
  },
  moj_baseline: {
    parameter: 'fixedCosts.justice',
    value: 55,
    unit: '£bn pa',
    confidence: 'extrapolated',
    title: 'UK justice and home affairs spending (2025-26)',
    publisher: 'HM Treasury / HoCL CBP-10280',
    year: 2025,
    url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10280/',
    note: 'MoJ resource budget + Home Office (police, immigration, security) + courts; aggregate ~£55bn pa per Spending Review 2025 envelopes.',
  },
  whole_govt_residual: {
    parameter: 'fixedCosts.otherDept',
    value: 302,
    unit: '£bn pa',
    confidence: 'extrapolated',
    title: 'Residual government spending (2025-26)',
    publisher: 'OBR Brief Guide / HM Treasury',
    year: 2025,
    url: 'https://obr.uk/forecasts-in-depth/brief-guides-and-explainers/public-finances/',
    note: 'Residual to reconcile sim total spending with the OBR Nov-2025 EFO £1,368bn aggregate. Covers devolved transfers, public-service pensions, DCMS, DEFRA, FCDO, DESNZ, environment, R&D, contingencies, and capital not captured in the infrastructure line.',
  },
  obr_nhs_baseline: {
    parameter: 'initial.spendNHS',
    value: 204,
    unit: '£bn pa',
    confidence: 'sourced',
    title: 'UK health (DHSC) spending 2025-26',
    publisher: 'OBR Brief Guide to the Public Finances',
    year: 2025,
    url: 'https://obr.uk/forecasts-in-depth/brief-guides-and-explainers/public-finances/',
    note: 'Health is the largest resource DEL line at £204bn in 2025-26 per the OBR brief guide. Verified via OBR Nov-2025 EFO summary tables.',
  },
  obr_edu_baseline: {
    parameter: 'initial.spendEdu',
    value: 95,
    unit: '£bn pa',
    confidence: 'sourced',
    title: 'UK education spending 2025-26',
    publisher: 'OBR Brief Guide to the Public Finances',
    year: 2025,
    url: 'https://obr.uk/forecasts-in-depth/brief-guides-and-explainers/public-finances/',
    note: 'Education resource DEL £95bn in 2025-26 per the OBR brief guide.',
  },
  obr_defence_baseline: {
    parameter: 'initial.spendDefence',
    value: 39,
    unit: '£bn pa',
    confidence: 'sourced',
    title: 'UK defence spending 2025-26',
    publisher: 'OBR Brief Guide to the Public Finances',
    year: 2025,
    url: 'https://obr.uk/forecasts-in-depth/brief-guides-and-explainers/public-finances/',
    note: 'Defence resource DEL £39bn in 2025-26 (the OBR brief guide top-three departments are health £204bn, education £95bn, defence £39bn). UK government plan is 2.5% then 3% of GDP, implying £77-93bn — the slider max captures that ramp.',
  },
  obr_welfare_baseline: {
    parameter: 'initial.spendWelfare',
    value: 187,
    unit: '£bn pa',
    confidence: 'sourced',
    title: 'UK working-age + children + disability welfare 2025-26',
    publisher: 'DWP / HoC Library CDP-2025-0035',
    year: 2025,
    url: 'https://commonslibrary.parliament.uk/research-briefings/cdp-2025-0035/',
    note: 'Total UK social security £333.7bn in 2025-26: state pension £146.1bn (handled separately in fixedCosts.pensions), pensioner non-pension benefits ~£32bn, working-age + children + disability ~£187bn (= £145bn working-age + children + £42bn disability/housing share net of pensioner overlap). This slider captures the discretionary chunk.',
  },
  obr_infra_baseline: {
    parameter: 'initial.spendInfra',
    value: 90,
    unit: '£bn pa',
    confidence: 'extrapolated',
    title: 'UK public-sector gross investment / infrastructure 2025-26',
    publisher: 'OBR Brief Guide / HoCL CBP-10280',
    year: 2025,
    url: 'https://obr.uk/forecasts-in-depth/brief-guides-and-explainers/public-finances/',
    note: 'Covers transport DEL + government capital investment (PSGI). Aligned with OBR 2025-26 capital DEL totals (~£90-100bn). High multiplier (OBR ~1.4).',
  },
  obr_local_baseline: {
    parameter: 'initial.spendLocal',
    value: 140,
    unit: '£bn pa',
    confidence: 'extrapolated',
    title: 'UK local government spending 2025-26',
    publisher: 'IFS / MHCLG / OBR',
    year: 2025,
    url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10280/',
    note: 'Local-government resource + capital, gross of council-tax financing. Sim previous value (£60bn) was net of council-tax which understated the gross expenditure line.',
  },
  initial_nominal_gdp: {
    parameter: 'GDP baseline for revenue scaling',
    value: 3100,
    unit: '£bn',
    confidence: 'sourced',
    title: 'UK nominal GDP 2025-26',
    publisher: 'ONS / OBR',
    year: 2025,
    url: 'https://www.ons.gov.uk/economy/grossdomesticproductgdp/bulletins/quarterlynationalaccounts/julytoseptember2025',
    note: 'ONS: nominal GDP £3,037bn for calendar-year 2025. Rounded to £3,100bn for 2025-26 fiscal year to allow for nominal growth into the simulation start period (Q1 2026). Used as baseline for revenue scaling.',
  },
  initial_population: {
    parameter: 'population baseline',
    value: 67.5,
    unit: 'millions',
    confidence: 'extrapolated',
    title: 'UK population 2025',
    publisher: 'ONS',
    year: 2025,
    url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates',
    note: 'Mid-year ~67.5m. Used as baseline for pension/locked-cost scaling.',
  },
  ons_baseline_pop_growth: {
    parameter: 'baseline annual population growth',
    value: 0.6,
    unit: '% pa',
    confidence: 'extrapolated',
    title: 'UK annual population growth',
    publisher: 'ONS',
    year: 2024,
    url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates',
    note: 'UK has averaged 0.5-1.0% annual population growth in recent years; ~0.6% used as midpoint.',
  },

  // ===========================================================================
  // Initial macro state
  // ===========================================================================
  obr_baseline_deficit: {
    parameter: 'initial debt level + deficit framing',
    value: 2950,
    unit: '£bn debt; £133bn deficit',
    confidence: 'sourced',
    title: 'UK fiscal position (2025-26)',
    publisher: 'OBR EFO Nov 2025 / ONS PSF',
    year: 2025,
    url: 'https://obr.uk/efo/economic-and-fiscal-outlook-november-2025/',
    note: 'OBR Nov-2025 EFO: PSNB £133bn (4.3% of GDP) in 2025-26. ONS Dec-2025 PSF bulletin: PSND ex banks 95.5% of GDP — at £3,100bn GDP this is ~£2,960bn debt; rounded to £2,950bn for the simulation.',
  },
  obr_growth_baseline: {
    parameter: 'starting real GDP growth',
    value: 1.1,
    unit: '% pa',
    confidence: 'sourced',
    title: 'OBR central growth forecast 2026',
    publisher: 'OBR EFO Nov 2025',
    year: 2025,
    url: 'https://obr.uk/efo/economic-and-fiscal-outlook-november-2025/',
    note: 'OBR Nov-2025 EFO central forecast: real GDP growth 1.1% in 2026.',
  },
  ons_inflation_baseline: {
    parameter: 'starting CPI inflation',
    value: 2.8,
    unit: '% pa',
    confidence: 'extrapolated',
    title: 'UK CPI inflation',
    publisher: 'ONS / BoE',
    year: 2024,
    url: 'https://www.ons.gov.uk/economy/inflationandpriceindices',
    note: 'Late-2024 CPI; converging on 2% target.',
  },
  ons_unemployment_baseline: {
    parameter: 'starting unemployment rate',
    value: 4.4,
    unit: '%',
    confidence: 'extrapolated',
    title: 'UK ILO unemployment rate',
    publisher: 'ONS',
    year: 2024,
    url: 'https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork',
    note: 'Approx Q3 2024.',
  },
  bond_yield_baseline: {
    parameter: 'starting market gilt yield (10-year)',
    value: 5.0,
    unit: '%',
    confidence: 'sourced',
    title: 'UK 10-year gilt yield, May 2026',
    publisher: 'Bank of England / DMO / Trading Economics',
    year: 2026,
    url: 'https://tradingeconomics.com/united-kingdom/government-bond-yield',
    note: 'Market 10-year gilt yield 5.07% on 12 May 2026 (an 18-year high). Drives market-sentiment dynamics and the endgame markets-revolt ceiling (8%). Does NOT drive debt-interest cost — see effective_servicing_rate_baseline for that, which captures the lower effective rate paid on the existing stock.',
  },
  effective_servicing_rate_baseline: {
    parameter: 'starting effective rate on debt stock',
    value: 3.7,
    unit: '%',
    confidence: 'sourced',
    title: 'UK effective debt-servicing rate 2025-26',
    publisher: 'OBR EFO Nov 2025 / Debt-interest forecast',
    year: 2025,
    url: 'https://obr.uk/forecasts-in-depth/tax-by-tax-spend-by-spend/debt-interest-central-government-net/',
    note: 'OBR Nov-2025 EFO: debt interest (net of APF) £110-111bn in 2025-26. At £2,950bn debt this implies an effective rate of ~3.73%. Distinct from the market gilt yield because most of the outstanding stock was issued when rates were lower; only new issuance / refinancing reflects the current market rate. Drifts toward the market yield over time (set to 5% of the gap per quarter) to model gradual refinancing as gilts mature.',
  },
  health_index_baseline: {
    parameter: 'starting health index',
    value: 68,
    unit: 'index 0-100',
    confidence: 'judgement',
    title: 'Composite UK Health Index baseline',
    note: 'Designer composite based loosely on ONS Health Index (England 2022 published value 99.0 vs 2015 base 100), HALE, and waiting-list pressures. Scaled to 0-100 game range.',
  },
  ons_gini_baseline: {
    parameter: 'starting Gini coefficient (post-tax disposable income, BHC)',
    value: 33.0,
    unit: 'Gini index',
    confidence: 'sourced',
    title: 'UK Gini coefficient for disposable income (FYE 2024-25, BHC)',
    publisher: 'ONS — Household income inequality',
    year: 2025,
    url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/personalandhouseholdfinances/incomeandwealth/bulletins/householdincomeinequalityfinancial/financialyearending2024',
    note: 'ONS: Gini for disposable income 33% BHC (37% AHC) for FYE 2024-25, unchanged from FYE 2024. The previous sim value (35.2) was pre-pandemic (FYE 2020 = 35.4%). BHC measure used as it sits closer to the conventional headline.',
  },

  // ===========================================================================
  // Endgame thresholds
  // ===========================================================================
  uk_election_cycle: {
    parameter: 'termLength',
    value: 20,
    unit: 'quarters',
    confidence: 'sourced',
    title: 'UK fixed-term Parliament (5 years)',
    note: 'Standard 5-year UK parliamentary term, set by the Dissolution and Calling of Parliament Act 2022.',
  },
  coalition_floor_judgement: {
    parameter: 'coalitionFloor',
    value: 22,
    unit: '% cohesion',
    confidence: 'judgement',
    title: 'Coalition-collapse threshold',
    note: 'Designer judgement — below this support level, the simulation treats coalition cohesion as catastrophically lost. Calibrated to game balance, not empirical.',
  },
  bond_yield_ceiling_judgement: {
    parameter: 'bondYieldCeiling',
    value: 8,
    unit: '% gilt yield',
    confidence: 'judgement',
    title: 'Markets-revolt bond-yield ceiling',
    note: 'Designer judgement loosely calibrated to 2022 mini-budget gilt-market stress (long-dated yields briefly above 5%). 8% represents an unmanageable cost-of-debt scenario.',
  },
  reelection_threshold_judgement: {
    parameter: 'reelectionCoalitionThreshold',
    value: 38,
    unit: '% cohesion at election',
    confidence: 'judgement',
    title: 'Re-election cohesion threshold',
    note: 'Designer judgement; chosen to give a realistic-feeling 5-year struggle to maintain.',
  },
  bloc_drift_judgement: {
    parameter: 'bloc-support drift coefficient toward baseline',
    value: 0.05,
    unit: 'fraction per quarter',
    confidence: 'judgement',
    title: 'Mean-reverting bloc support drift',
    note: 'Designer-set; each quarter, bloc support drifts 5% of the gap back toward its baseline (per quarter, before /4 conversion). Models limited persistence of policy shocks on opinion.',
  },
  honeymoon_reset_judgement: {
    parameter: 'post-election bloc reset (0.7/0.3 mix)',
    value: 0.7,
    unit: 'weight toward current vs baseline',
    confidence: 'judgement',
    title: 'Re-elected honeymoon reset',
    note: 'After re-election, each bloc support resets to 70% of its current value plus 30% of its baseline. Designer-set "honeymoon" effect.',
  },
  bond_yield_response_judgement: {
    parameter: 'bond yield response to balance (per-quarter)',
    confidence: 'judgement',
    title: 'Quarterly gilt-yield adjustment',
    note: 'Quarterly bond-yield adjustments responding to fiscal balance are designer-set: -£200bn balance → +0.08pp; -£100bn → +0.02pp; surplus → -0.06pp; mild deficit → -0.03pp. Models market sentiment toward fiscal stance.',
  },

  // ===========================================================================
  // Bloc-response coefficients (all judgement; share bloc_methodology note)
  // ===========================================================================
  bloc_response_basic_rate: {
    parameter: 'blocResponses.basicRate',
    confidence: 'judgement',
    title: 'Bloc reactions to basic rate income tax changes',
    note: 'Working class, youth, pensioners, middle class, northern, ethnic minority all hostile to basic-rate rises and friendly to cuts. Magnitudes are designer judgements. See bloc_methodology.',
  },
  bloc_response_higher_rate: {
    parameter: 'blocResponses.higherRate',
    confidence: 'judgement',
    title: 'Bloc reactions to higher rate income tax changes',
    note: 'Middle class and professionals most sensitive; public sector mildly so. Designer judgement. See bloc_methodology.',
  },
  bloc_response_additional_rate: {
    parameter: 'blocResponses.additionalRate',
    confidence: 'judgement',
    title: 'Bloc reactions to additional rate income tax changes',
    note: 'Working class & northern friendly to rises (redistributive signal); business & professional hostile. Magnitudes designer-set.',
  },
  bloc_response_corp_rate: {
    parameter: 'blocResponses.corpTax',
    confidence: 'judgement',
    title: 'Bloc reactions to corporation tax',
    note: 'Above 28%: business strongly hostile, professional mildly so. Below 22%: working class and public sector hostile (perceived as giveaway). Designer-set thresholds.',
  },
  bloc_response_vat: {
    parameter: 'blocResponses.vat',
    confidence: 'judgement',
    title: 'Bloc reactions to VAT changes',
    note: 'VAT regressivity recognised by all redistributive-coded blocs. Working class, pensioners, northern, ethnic minority strongly hostile to rises. Magnitudes designer-set; calibrated higher than income-tax magnitudes to reflect VAT salience.',
  },
  bloc_response_nhs_spend: {
    parameter: 'blocResponses.nhsSpending',
    confidence: 'judgement',
    title: 'Bloc reactions to NHS spending',
    note: 'Pensioners, public sector, working class, northern react strongly to cuts below £204bn baseline. Public sector, pensioners, middle class reward sustained boosts above £214bn.',
  },
  bloc_response_welfare_spend: {
    parameter: 'blocResponses.welfareSpending',
    confidence: 'judgement',
    title: 'Bloc reactions to welfare spending',
    note: 'Working class, northern, ethnic minority, youth all hostile to cuts below £177bn baseline (working-age + children + disability scope; state pension is locked AME and not on this slider). Designer-set.',
  },
  bloc_response_edu_spend: {
    parameter: 'blocResponses.educationSpending',
    confidence: 'judgement',
    title: 'Bloc reactions to education spending',
    note: 'Youth, public sector, working class react to cuts below £90bn baseline.',
  },
  bloc_response_local_spend: {
    parameter: 'blocResponses.localGovSpending',
    confidence: 'judgement',
    title: 'Bloc reactions to local government spending',
    note: 'Public sector, middle class, working class react to cuts below the £140bn baseline.',
  },
  bloc_response_infra_spend: {
    parameter: 'blocResponses.infraSpending',
    confidence: 'judgement',
    title: 'Bloc reactions to infrastructure spending',
    note: 'Business and northern blocs reward infrastructure boosts above £95bn (£5bn over the £90bn baseline).',
  },

  // ===========================================================================
  // Risk register base rates (annual probabilities; designer-set)
  // ===========================================================================
  nhs_strike_base: {
    parameter: 'risks.nhsStrike.base',
    value: 25,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'NHS strike base rate',
    note: 'Designer-set; calibrated against 2022-24 strike-action frequency (RCN, BMA, junior doctors). See event_probability_methodology.',
  },
  nhs_strike_funding_response: {
    parameter: 'risks.nhsStrike.perBnUnderfunded',
    value: 1.5,
    unit: '+pp per £bn under baseline',
    confidence: 'judgement',
    title: 'NHS strike sensitivity to funding',
    note: 'Designer judgement; below £200bn baseline each £bn shortfall adds 1.5pp to strike probability.',
  },
  energy_shock_base: {
    parameter: 'risks.energyShock.base',
    value: 18,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Global energy price shock base rate',
    note: 'Designer-set; reflects 2022-23 frequency of major global energy disruptions.',
  },
  fuel_poverty_base: {
    parameter: 'risks.fuelPoverty.base',
    value: 15,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Winter fuel poverty crisis base rate',
    note: 'Designer-set.',
  },
  fuel_poverty_welfare_response: {
    parameter: 'risks.fuelPoverty.perBnWelfareUnderfunded',
    value: 0.3,
    unit: '+pp per £bn under baseline',
    confidence: 'judgement',
    title: 'Fuel poverty sensitivity to welfare cuts',
    note: 'Designer judgement.',
  },
  housing_crisis_base: {
    parameter: 'risks.housingCrisis.base',
    value: 22,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Homelessness/housing crisis base rate',
    note: 'Designer-set; reflects elevated rough-sleeping trend pre-simulation.',
  },
  council_bankruptcy_base: {
    parameter: 'risks.councilBankruptcy.base',
    value: 12,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Council Section 114 base rate',
    note: 'Designer-set; calibrated to 2022-24 Section 114 frequency (Birmingham, Croydon, Slough, Thurrock, Woking).',
  },
  council_bankruptcy_local_response: {
    parameter: 'risks.councilBankruptcy.perBnLocalUnderfunded',
    value: 1.8,
    unit: '+pp per £bn under baseline',
    confidence: 'judgement',
    title: 'Council bankruptcy sensitivity to local-gov funding',
    note: 'Designer judgement.',
  },
  council_bankruptcy_carecrisis_response: {
    parameter: 'risks.careCrisis.localUnderfundedKick',
    value: 5,
    unit: '+pp when local underfunded',
    confidence: 'judgement',
    title: 'Care crisis kick when local gov underfunded',
    note: 'Designer judgement; council underfunding correlates with care-sector failures.',
  },
  financial_crisis_base: {
    parameter: 'risks.financialCrisis.base',
    value: 6,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Banking sector stress base rate',
    note: 'Designer-set; low base probability for a major UK banking failure.',
  },
  general_strike_base: {
    parameter: 'risks.generalStrike.base',
    value: 8,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Cross-sector strike wave base rate',
    note: 'Designer-set.',
  },
  general_strike_tax_response: {
    parameter: 'risks.generalStrike.taxRiseKick',
    confidence: 'judgement',
    title: 'General strike sensitivity to basic-rate and VAT rises',
    note: 'Designer judgement: basic rate >22% adds 8pp; VAT >22% adds 6pp.',
  },
  care_crisis_base: {
    parameter: 'risks.careCrisis.base',
    value: 14,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Care sector collapse base rate',
    note: 'Designer-set; reflects recurring large care-operator failures.',
  },
  flood_base: {
    parameter: 'risks.flood.base',
    value: 10,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Severe flooding base rate',
    note: 'Designer-set; broadly consistent with EA flooding event frequency.',
  },
  heatwave_base: {
    parameter: 'risks.heatwave.base',
    value: 8,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Record heatwave base rate',
    note: 'Designer-set; rising with climate trend.',
  },
  trade_deal_base: {
    parameter: 'risks.tradeDeal.base',
    value: 5,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Major trade agreement base rate',
    note: 'Designer-set; low base rate for genuinely material trade deal.',
  },
  ally_crisis_base: {
    parameter: 'risks.allyCrisis.base',
    value: 7,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'NATO ally crisis base rate',
    note: 'Designer-set.',
  },
  investment_surge_base: {
    parameter: 'risks.investmentSurge.base',
    value: 8,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Foreign investment surge base rate',
    note: 'Designer-set; raised by skills/infra reforms.',
  },
  investment_surge_infra_response: {
    parameter: 'risks.investmentSurge.perBnInfraOverbaseline',
    value: 0.3,
    unit: '+pp per £bn over baseline',
    confidence: 'judgement',
    title: 'Investment-surge sensitivity to infra spending',
    note: 'Designer judgement; above £45bn infra each £bn adds 0.3pp probability.',
  },
  export_boom_base: {
    parameter: 'risks.exportBoom.base',
    value: 6,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Export surge base rate',
    note: 'Designer-set.',
  },
  productivity_jump_base: {
    parameter: 'risks.productivityJump.base',
    value: 5,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Productivity surprise base rate',
    note: 'Designer-set; reflects rarity of significant UK productivity good news.',
  },
  tax_beats_base: {
    parameter: 'risks.taxBeats.base',
    value: 7,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Tax receipts beat forecast base rate',
    note: 'Designer-set.',
  },
  demographic_dividend_base: {
    parameter: 'risks.demographicDividend.base',
    value: 4,
    unit: '% pa probability',
    confidence: 'judgement',
    title: 'Demographic dividend (workforce participation surge) base rate',
    note: 'Designer-set.',
  },
  labour_shortage_base: {
    parameter: 'risks.labourShortage.base',
    value: 0,
    unit: '% pa probability (gated)',
    confidence: 'judgement',
    title: 'Severe labour shortage base rate',
    note: 'Zero by default; triggered only by immigration cap reform (+25pp).',
  },
  risk_caps_judgement: {
    parameter: 'risk probability caps (1% min, 90% max)',
    confidence: 'judgement',
    title: 'Risk-modifier clamp range',
    note: 'Designer-set clamping to keep all risks in [1%, 90%] pa range.',
  },

  // ===========================================================================
  // Population dynamics
  // ===========================================================================
  ons_baseline_quarterly_pop: {
    parameter: 'baseline quarterly population growth (overall)',
    value: 0.15,
    unit: '% per quarter',
    confidence: 'extrapolated',
    title: 'UK quarterly population growth',
    publisher: 'ONS',
    year: 2024,
    url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates',
    note: '0.6% pa / 4 = 0.15% per quarter. UK long-run trend.',
  },
  bloc_pop_growth_judgement: {
    parameter: 'per-bloc baseline population drift',
    confidence: 'judgement',
    title: 'Bloc demographic drift rates',
    note: 'Designer-set drift rates for each bloc (pensioners +0.4%/y; working class -0.1%; etc.) reflect broad UK demographic trends (ageing, knowledge-economy professional growth, shrinking youth cohort) but specific magnitudes are designer judgements.',
  },

  // ===========================================================================
  // Reform: revenue branch
  // ===========================================================================
  nao_hmrc_compliance: {
    parameter: 'hmrcCapacity reform',
    value: 4,
    unit: '£bn pa revBonus',
    confidence: 'sourced',
    title: 'UK tax gap measurements and compliance ROI',
    publisher: 'HMRC / NAO / PAC',
    year: 2023,
    url: 'https://www.gov.uk/government/statistics/measuring-tax-gaps',
    note: 'Verified: HMRC tax gap originally published as £39.8bn (4.8%) for 2022-23 (later revised to £46.4bn). PAC-cited compliance ROI was £18 per £1 invested (2021-22); current ratio ~£23:£1 (2024-25). Simulation £4bn pa modernisation return is a modest fraction of full tax gap and well within stated ROI ranges.',
  },
  obr_independence_judgement: {
    parameter: 'obrIndependence reform',
    confidence: 'judgement',
    title: 'OBR Independence — forecast-noise reduction',
    note: 'Designer judgement; statutory OBR strengthening narrows in-game ±25% forecast band to ±10%. Real OBR has identified ~£20bn pa optimistic departmental costings; precise noise reduction is a game-design choice.',
  },
  ifs_cgt_alignment: {
    parameter: 'cgtAlign reform',
    value: 13,
    unit: '£bn pa revBonus',
    confidence: 'extrapolated',
    title: 'Capital Gains Tax Reform',
    publisher: 'IFS / CenTax',
    authors: ['Stuart Adam', 'Arun Advani', 'Helen Miller', 'Andy Summers'],
    year: 2024,
    url: 'https://ifs.org.uk/publications/capital-gains-tax-reform',
    note: 'Source range: ~£14bn pa for the FULL CGT reform package (rate alignment + uplift-at-death + base reform); worst-case behavioural-response scenario £9.6bn. Simulation uses £13bn for "rate alignment" alone, which conflates package vs alignment-only; treat as in-range extrapolation.',
  },
  cgt_gini_judgement: {
    parameter: 'cgtAlign gini effect',
    value: -0.3,
    unit: 'gini points',
    confidence: 'judgement',
    title: 'CGT alignment distributional effect',
    note: "Designer judgement; CGT receipts concentrated in top 1% so alignment is progressive. -0.3 Gini approximates an IFS-style distributional analysis but is not directly costed.",
  },
  centax_nondom: {
    parameter: 'nondomEnd reform',
    value: 4,
    unit: '£bn pa revBonus',
    confidence: 'extrapolated',
    title: 'The UK Non-Dom Regime: Implications of Reform',
    publisher: 'CenTax / LSE / Warwick',
    authors: ['Arun Advani', 'Cesar Burgherr', 'Andy Summers'],
    year: 2025,
    url: 'https://centax.org.uk/research/',
    note: 'Verified: 2017 reform caused -4.9% departures (stock elasticity 0.26) while tax paid by those remaining rose >150% (Income Tax up ~£100k per remaining person pa). CenTax/LSE non-dom abolition headline estimate is £3.2bn pa (CAGE variant: £3.6bn). Simulation uses £4bn — slightly above source range, treat as a small judgement uplift.',
  },
  wealth_tax_commission: {
    parameter: 'wealthTax reform',
    value: 24,
    unit: '£bn pa revBonus',
    confidence: 'judgement',
    title: 'A Wealth Tax for the UK',
    publisher: 'Wealth Tax Commission',
    authors: ['Arun Advani', 'Emma Chamberlain', 'Andy Summers'],
    year: 2020,
    url: 'https://www.wealthandpolicy.com/',
    note: 'DESIGNER FRAMING: Wealth Tax Commission explicitly recommended a ONE-OFF 5% levy on wealth >£500k (~£260bn revenue), NOT an annual rate. £24bn pa from 2% above £10m is at the top of a £12-24bn range from secondary commentary, not the Commission\'s recommendation. Classified judgement per user decision: the simulation\'s annual-tax framing is not what the source proposes. Migration response (<0.1) is consistent with Young et al. (2016) — see young_millionaire_migration.',
  },
  wealth_tax_migration_judgement: {
    parameter: 'wealthTax migration response',
    confidence: 'judgement',
    title: 'Wealth tax migration response',
    note: "Simulation assumes <0.1 semi-elasticity per Young et al. (2016). 'Migration response <0.1' framing in completion log is consistent with US millionaire-migration research.",
  },
  hmrc_charity_credit: {
    parameter: 'charityCredit reform',
    value: 2,
    unit: '£bn pa revBonus',
    confidence: 'extrapolated',
    title: 'UK Charity Tax Relief Statistics 2024-25',
    publisher: 'HMRC',
    year: 2024,
    url: 'https://www.gov.uk/government/statistics/cost-of-tax-relief',
    note: 'Verified baseline: HMRC June 2025 statistics confirm total charity reliefs £6.7bn (2024-25, +5%) including £820m higher-rate Gift Aid donor relief (+8%). Simulation £2bn pa revBonus from deduction→credit conversion is a designer-derived figure from this baseline (not a published costing).',
  },
  windfall_levy: {
    parameter: 'windfallTax reform',
    value: 8,
    unit: '£bn pa revBonus',
    confidence: 'extrapolated',
    title: 'Energy Profits Levy and proposed multi-sector windfall',
    publisher: 'HMRC / IFS',
    year: 2024,
    url: 'https://ifs.org.uk/green-budget',
    note: 'Existing Energy Profits Levy raises ~£3bn pa; multi-sector extension (energy + banking + retail) calibrated to ~£8bn pa.',
  },
  ifs_employer_ni: {
    parameter: 'niEmployer reform',
    value: 7,
    unit: '£bn pa revBonus',
    confidence: 'extrapolated',
    title: 'IFS Green Budget — employment income alignment',
    publisher: 'IFS',
    year: 2024,
    url: 'https://ifs.org.uk/green-budget',
    note: 'IFS analyses alignment of employment/self-employment/dividend tax treatment as raising ~£8bn pa; simulation rounds to £7bn for the Employer-NI-on-investment-income variant.',
  },
  ifs_benefit_freeze: {
    parameter: 'benefitFreeze reform',
    value: 6,
    unit: '£bn pa revBonus',
    confidence: 'extrapolated',
    title: 'Benefit freeze savings (2016-2020)',
    publisher: 'IFS',
    year: 2020,
    url: 'https://ifs.org.uk/publications/effect-benefit-freeze',
    note: 'The 2016-2020 benefit freeze saved ~£4bn pa and pushed ~400k children into poverty. Three-year extended freeze costed at £6bn pa.',
  },
  benefit_freeze_health_judgement: {
    parameter: 'benefitFreeze health/Gini effects',
    confidence: 'judgement',
    title: 'Benefit freeze distributional & health effects',
    note: 'Gini +0.4 and healthBoost -2 are designer judgements consistent with IFS poverty-impact analysis but not directly published values.',
  },
  hope_limberg_top_rate: {
    parameter: 'topRateCut reform',
    value: -5,
    unit: '£bn pa ongoingRev',
    confidence: 'sourced',
    title: 'The Economic Consequences of Major Tax Cuts for the Rich',
    publisher: 'Socio-Economic Review (LSE/KCL)',
    authors: ['David Hope', 'Julian Limberg'],
    year: 2022,
    url: 'https://academic.oup.com/ser/article/20/2/539/6500315',
    note: 'Verified: Hope & Limberg study 18 OECD countries 1965-2015 (~50 years) and find tax cuts for the rich significantly raise top inequality but have NO significant effect on real GDP growth or unemployment 5y post-reform. Simulation models -£5bn pa revenue cost with no growth offset.',
  },

  // ===========================================================================
  // Reform: NHS & care branch
  // ===========================================================================
  nhs_pay_settlement: {
    parameter: 'nhsPay reform',
    value: 4,
    unit: '£bn pa ongoingCost',
    confidence: 'extrapolated',
    title: 'NHS pay settlement & agency spend',
    publisher: 'NHS England Annual Report',
    year: 2023,
    url: 'https://www.england.nhs.uk/',
    note: 'NHS agency spend ~£3bn pa pre-deal; multi-year pay settlement net cost ~£4bn pa with ~£1bn agency-spend reduction.',
  },
  nhs_strike_payDeal_effect: {
    parameter: 'risks.nhsStrike.payDealReduction',
    value: -50,
    unit: '-pp probability',
    confidence: 'judgement',
    title: 'NHS pay deal strike-risk reduction',
    note: 'Designer judgement; multi-year pay deal cuts NHS strike risk by 50pp.',
  },
  dilnot_social_care: {
    parameter: 'dilnotCap reform',
    value: 5,
    unit: '£bn pa ongoingCost',
    confidence: 'extrapolated',
    title: 'Dilnot-style social care funding',
    publisher: 'Department of Health & Social Care / OBR / HoC Library',
    year: 2021,
    url: 'https://www.gov.uk/government/publications/build-back-better-our-plan-for-health-and-social-care',
    note: 'CORRECTION: original £3.6bn was a 3-year PACKAGE total (not pa); projected annual costs £1.4bn (2023/24) rising to £4.7bn (2031/32, 2021/22 prices). Cap policy was abandoned July 2024. Simulation £5bn pa is at the upper end of out-year projections; treat as in-range extrapolation for a more generous Dilnot variant.',
  },
  marmot_preventative: {
    parameter: 'preventativeHealth reform',
    confidence: 'sourced',
    title: 'Health Inequalities, Lives Cut Short (Marmot 2024)',
    publisher: 'Institute of Health Equity, UCL',
    authors: ['Michael Marmot'],
    year: 2024,
    url: 'https://www.instituteofhealthequity.org/',
    note: 'Verified: ~148,000 excess deaths attributable to austerity 2011-pandemic (Marmot/IHE 2024). Simulation costing (£3bn upfront / £2bn ongoing / +0.2pp growth / +4 health) is a designer-set programme size; the 148k mortality framing is sourced.',
  },
  nhs_mental_health_parity: {
    parameter: 'mentalHealth reform',
    value: 3,
    unit: '£bn pa ongoingCost',
    confidence: 'extrapolated',
    title: 'NHS mental health funding parity',
    publisher: 'NHS England Mental Health Dashboard',
    year: 2024,
    url: 'https://www.england.nhs.uk/mental-health/',
    note: 'NHS mental health spend ~£17bn of ~£200bn; parity would raise to ~£24bn (+£7bn). Simulation models £3bn ongoing as a partial-parity step.',
  },
  bmj_nhs_private: {
    parameter: 'privatiseNHS reform',
    confidence: 'extrapolated',
    title: 'NHS private provision cost analysis',
    publisher: 'BMJ studies (various)',
    year: 2023,
    url: 'https://www.bmj.com/',
    note: 'BMJ analyses of privatised NHS provision find per-procedure costs ~10-25% higher over time. Simulation models +£2bn pa ongoing cost with +1 health boost.',
  },

  // ===========================================================================
  // Reform: Housing branch
  // ===========================================================================
  shelter_social_housing: {
    parameter: 'socialHousing reform',
    confidence: 'extrapolated',
    title: 'Building the Homes We Need',
    publisher: 'Shelter',
    year: 2024,
    url: 'https://england.shelter.org.uk/professional_resources/policy_and_research',
    note: 'Shelter estimates £10bn/year for ~90k social homes/year. Simulation uses £8bn upfront for 300k homes over 8Q (≈37.5k/Q ≈ 150k/year, scaled for budget).',
  },
  planning_friction: {
    parameter: 'planningReform reform',
    confidence: 'extrapolated',
    title: 'Housebuilding Market Study',
    publisher: 'Competition and Markets Authority',
    year: 2024,
    url: 'https://www.gov.uk/cma-cases/housebuilding-market-study',
    note: 'CMA finds planning friction reduces housing supply by ~30%. Simulation models +0.2pp growth from presumption-in-favour reform.',
  },
  diamond_mcquade_qian_rent_control: {
    parameter: 'rentControls reform',
    confidence: 'sourced',
    title: 'The Effects of Rent Control Expansion on Tenants, Landlords, and Inequality',
    publisher: 'American Economic Review 109(9)',
    authors: ['Rebecca Diamond', 'Tim McQuade', 'Franklin Qian'],
    year: 2019,
    url: 'https://www.aeaweb.org/articles?id=10.1257/aer.20181289',
    note: 'Verified: San Francisco rent-control study finds controls reduce renter mobility 20% (protecting incumbents) but landlords cut rental supply 15% via sales to owner-occupiers / redevelopment, raising citywide rents 5.1%. Simulation -0.2 Gini and -0.05pp growth are designer-set magnitudes consistent with the paper\'s qualitative findings.',
  },
  right_to_buy_end_judgement: {
    parameter: 'rightToBuyEnd reform',
    confidence: 'judgement',
    title: 'End Right-to-Buy distributional effect',
    note: 'Designer judgement: ~2m homes sold since 1980; ending sale (~10k/year erosion) preserves stock. -0.1 Gini effect is judgement-based.',
  },

  // ===========================================================================
  // Reform: Green / infrastructure branch
  // ===========================================================================
  gb_energy_grid: {
    parameter: 'greenInvest reform',
    confidence: 'extrapolated',
    title: 'GB Energy and grid investment',
    publisher: 'Labour Party manifesto / National Grid analysis',
    year: 2024,
    url: 'https://labour.org.uk/manifesto/',
    note: 'Labour committed £8.3bn over 5 years for GB Energy; grid needs ~£40bn through 2030 (National Grid ESO). Simulation rounds to £10bn upfront.',
  },
  ccc_insulation: {
    parameter: 'insulationScheme reform',
    confidence: 'extrapolated',
    title: 'Net Zero / Carbon Budget — building retrofit',
    publisher: 'Climate Change Committee',
    year: 2024,
    url: 'https://www.theccc.org.uk/',
    note: 'CCC: retrofit programme ~£15bn over 5y; saves ~£300/year per household. Simulation models £4bn upfront for accelerated phase.',
  },
  npr_rail: {
    parameter: 'rail reform',
    confidence: 'extrapolated',
    title: 'Northern Powerhouse Rail',
    publisher: 'Department for Transport / NPR business case',
    year: 2024,
    url: 'https://www.gov.uk/government/collections/northern-powerhouse-rail',
    note: 'Full NPR scheme ~£70bn over 10y; £12bn over 12Q models a first-phase commitment with +0.5pp growth.',
  },
  cebr_full_fibre: {
    parameter: 'digitalInfra reform',
    confidence: 'sourced',
    title: 'Full Fibre: Economic Impact',
    publisher: 'CEBR (for Openreach)',
    year: 2022,
    url: 'https://cebr.com/',
    note: 'Verified: CEBR study for Openreach estimates full-fibre rollout to all UK premises by end-2025 boosts annual GVA by £59bn (£1,700+ per worker), rising to £70bn by 2038. Simulation £5bn upfront / +0.2pp growth is conservative against the £59bn GVA range.',
  },
  deregulation_judgement: {
    parameter: 'deregulate reform',
    confidence: 'judgement',
    title: 'Deregulation growth effect',
    note: 'OECD evidence on light-touch regulation is mixed and sector-specific. Simulation gives +0.15pp growth, but adds riskMods of +5pp financial crisis and +3pp flood, reflecting contested evidence.',
  },

  // ===========================================================================
  // Reform: Education / labour / state branches
  // ===========================================================================
  resolution_childcare: {
    parameter: 'freeChildcare reform',
    confidence: 'extrapolated',
    title: 'Childcare and labour supply',
    publisher: 'Resolution Foundation',
    year: 2023,
    url: 'https://www.resolutionfoundation.org/',
    note: 'RF: universal free childcare ~£8bn pa cost returns ~£12bn via labour supply. Simulation: £5bn upfront / £6bn ongoing / +0.4pp growth.',
  },
  ifs_fe_funding: {
    parameter: 'skillsBudget reform',
    confidence: 'extrapolated',
    title: 'Further Education funding analysis',
    publisher: 'IFS',
    year: 2022,
    url: 'https://ifs.org.uk/publications/further-education-and-sixth-form-spending',
    note: 'IFS: FE funding cut 14% real terms 2010-2020. Restoration ~£3bn pa with modest growth boost.',
  },
  obr_tuition_fees: {
    parameter: 'uniReform reform',
    confidence: 'extrapolated',
    title: 'Student loan RAB charge',
    publisher: 'OBR / DfE',
    year: 2023,
    url: 'https://obr.uk/',
    note: 'Current student-loan RAB charge ~44%; graduate-tax replacement costed ~£3bn pa ongoing.',
  },
  lpc_living_wage: {
    parameter: 'realLivingWage reform',
    confidence: 'extrapolated',
    title: 'National Living Wage and Real Living Wage analysis',
    publisher: 'Low Pay Commission',
    year: 2024,
    url: 'https://www.gov.uk/government/organisations/low-pay-commission',
    note: 'LPC: Real Living Wage (~£12.60/hr) ~5%+ above NLW; ~2.4m workers; ONS finds limited employment effects.',
  },
  oecd_sectoral_bargaining: {
    parameter: 'unionRights reform',
    confidence: 'extrapolated',
    title: 'OECD on collective bargaining systems',
    publisher: 'OECD',
    year: 2019,
    url: 'https://www.oecd.org/employment/negotiating-our-way-up-1fd2da34-en.htm',
    note: 'OECD: countries with sectoral bargaining have lower wage inequality. Repealing 2016 Act + sectoral frameworks → -0.2 Gini.',
  },
  jager_codetermination: {
    parameter: 'workersBoardSeats reform',
    confidence: 'judgement',
    title: 'Labor in the Boardroom',
    publisher: 'Quarterly Journal of Economics 136(2)',
    authors: ['Simon Jäger', 'Benjamin Schoefer', 'Jörg Heining'],
    year: 2021,
    url: 'https://academic.oup.com/qje/article/136/2/669/6041122',
    note: "Source: Jäger, Schoefer & Heining (2021) find German codetermination raises long-term capital stock 40-50% but has no significant effect on wages, wage structure, or labour share. The simulation's +0.1pp growth and -0.2 Gini are designer judgements informed by the wider codetermination literature; the often-cited '~1% productivity' figure is NOT in the QJE paper itself.",
  },
  ilo_minimum_service: {
    parameter: 'antiStrike reform',
    confidence: 'extrapolated',
    title: 'ILO conventions on freedom of association',
    publisher: 'International Labour Organization',
    year: 2023,
    url: 'https://www.ilo.org/global/standards/',
    note: 'ILO has criticised similar minimum-service-levels laws as breaching international labour standards. Simulation gives no revenue or growth gain; bloc effects negative on workers/public sector.',
  },
  nao_civil_service: {
    parameter: 'civilService reform',
    confidence: 'extrapolated',
    title: 'Civil service consultancy spend',
    publisher: 'NAO / Cabinet Office',
    year: 2023,
    url: 'https://www.nao.org.uk/',
    note: 'Civil service consultancy spend hit £2.8bn in 2022-23. Rebuilding capacity (£2bn upfront / £1bn ongoing) returns ~£2bn pa via reduced consultancy reliance.',
  },
  ifs_local_gov: {
    parameter: 'localGov reform',
    confidence: 'extrapolated',
    title: 'Local government funding analysis',
    publisher: 'IFS',
    year: 2022,
    url: 'https://ifs.org.uk/publications/local-government-finances',
    note: 'IFS: real-terms council funding fell 25% 2010-2020. Multi-year settlement (£5bn ongoing) reduces council-bankruptcy risk by 20pp.',
  },
  bcbs_capital_reqs: {
    parameter: 'banking reform',
    confidence: 'extrapolated',
    title: 'Basel Committee on Banking Supervision — capital requirements',
    publisher: 'BCBS / BIS',
    year: 2017,
    url: 'https://www.bis.org/bcbs/publ/d424.htm',
    note: 'BCBS analyses: 1pp higher capital requirement reduces crisis probability by ~0.5pp. Simulation: -4pp financial-crisis risk from higher requirements + ring-fence enforcement.',
  },
  obr_migration_cap: {
    parameter: 'immigrationCap reform',
    confidence: 'extrapolated',
    title: 'Migration analysis box',
    publisher: 'OBR Economic and Fiscal Outlook (November 2023)',
    year: 2023,
    url: 'https://obr.uk/efo/economic-and-fiscal-outlook-november-2023/',
    note: 'Each 100k of net migration adds ~0.5% real GDP over 5 years. Cap to 100k modelled as -0.4pp growth, -£3bn ongoing revenue, and negative bloc-population effects.',
  },
  young_millionaire_migration: {
    parameter: 'wealthTax / nondom migration response',
    confidence: 'sourced',
    title: 'Millionaire Migration and Taxation of the Elite',
    publisher: 'American Sociological Review 81(3)',
    authors: ['Cristobal Young', 'Charles Varner', 'Ithai Lurie', 'Richard Prisinzano'],
    year: 2016,
    url: 'https://journals.sagepub.com/doi/10.1177/0003122416639625',
    note: 'Verified: 45m IRS tax records covering 3.7m millionaire filers (1999-2011); migration elasticity η ≈ 0.1 — very low tax-induced mobility. Cross-walked to UK non-dom and wealth-tax migration framings in-game.',
  },
  pac_rwanda: {
    parameter: 'refugeeRestrict reform',
    confidence: 'extrapolated',
    title: 'Rwanda scheme cost analysis',
    publisher: 'Public Accounts Committee',
    year: 2024,
    url: 'https://committees.parliament.uk/committee/127/public-accounts-committee/',
    note: 'PAC: Rwanda asylum scheme cost £700m+ for zero removals. Simulation models £2bn upfront with no fiscal benefit and significant negative bloc effects.',
  },
  obr_triple_lock_plus: {
    parameter: 'triple_lock_plus reform',
    value: 8,
    unit: '£bn pa ongoingCost',
    confidence: 'extrapolated',
    title: 'Triple Lock Plus costing',
    publisher: 'OBR',
    year: 2024,
    url: 'https://obr.uk/',
    note: 'OBR: extending the triple lock costs ~£8bn cumulative by 2030. Simulation uses £8bn pa as ongoing cost for game balance.',
  },

  // ===========================================================================
  // Surplus allocation parameters (designer-set)
  // ===========================================================================
  surplus_allocation_judgement: {
    parameter: 'surplus allocation effects (services boost, tax-cut bloc reactions)',
    confidence: 'judgement',
    title: 'Surplus allocation game mechanics',
    note: 'Pay-down-debt is 1:1. Services boost: health +allocation/8, working-class +alloc/10, public-sector +alloc/12, pensioners +alloc/14. Tax-cut bloc reactions: middle +alloc/8, business +alloc/6, professional +alloc/10. All ratios designer-set.',
  },

  // ===========================================================================
  // Event payouts (debt/growth/bloc deltas in EVENT_DEFINITIONS)
  //
  // Each event has its own citation; magnitudes within a choice's effect are
  // attributed to that event's entry. Designer judgement throughout, but the
  // note records the scale-of-event reasoning for each one.
  // ===========================================================================
  event_nhs_strike: {
    parameter: 'nhsStrike event choice effects',
    confidence: 'judgement',
    title: 'NHS strike — choice payouts',
    note: 'RCN/BMA strikes in 2022–24 produced £1–4bn negotiated pay-deal envelopes (RCN settlement ~£3bn cumulative one-off). Anti-strike legislation (Minimum Service Levels Act 2023) drew sharp public-sector and union pushback (YouGov pollers showed -12 to -15 net favourability among public-sector workers). "Wait it out" reflects evidence from 2022 ambulance disputes that prolonged action raises excess-mortality estimates (3–5 health-index pp equivalent). Bloc magnitudes scaled to the event lens.',
  },
  event_energy_shock: {
    parameter: 'energyShock event choice effects',
    confidence: 'judgement',
    title: 'Energy price shock — choice payouts',
    note: 'EPG-style intervention (Truss/Sunak Oct-2022) cost ~£12bn for two quarters of a 60% gas spike. Targeted-support + windfall mirrors EPGT + EPL design (Sunak May-2022 / Hunt Nov-2022): cheaper to Exchequer (~£3bn net after windfall receipts) but more visibly anti-business. "Let the market clear" payouts reflect 2022 fuel-poverty modelling (NEA, Resolution Foundation) and one-off inflationary passthrough of ~1.5pp.',
  },
  event_fuel_poverty: {
    parameter: 'fuelPoverty event choice effects',
    confidence: 'judgement',
    title: 'Winter fuel poverty — choice payouts',
    note: 'Age UK 2024 estimates ~2.5m pensioners in fuel poverty. £4bn emergency winter-payment scale matches 2022/23 Cost of Living Payments package. Council-route is cheaper but smaller reach. "Refuse" magnitudes calibrated against Marmot Review excess winter death evidence (a few thousand excess deaths in cold winters).',
  },
  event_housing_crisis: {
    parameter: 'housingCrisis event choice effects',
    confidence: 'judgement',
    title: 'Homelessness surge — choice payouts',
    note: 'MHCLG rough-sleeping rises (+33% 2022–24, Shelter). £2bn emergency homelessness fund matches Everyone In (~£2bn one-off, 2020). CPO-on-empties is cheaper (~£1bn) but contests property rights (business penalty). "Tough on rough sleeping" magnitudes reflect 2022 Public Order Bill polling backlash.',
  },
  event_council_bankruptcy: {
    parameter: 'councilBankruptcy event choice effects',
    confidence: 'judgement',
    title: 'Council Section 114 — choice payouts',
    note: 'Recent S114s (Birmingham, Croydon, Thurrock, Woking) needed £0.5–3bn central support combined. Direct bailout vs. commissioners (LAPS regime) is the standard binary; commissioner route is cheaper but historically unpopular with affected councils and northern/midlands voters.',
  },
  event_financial_crisis: {
    parameter: 'financialCrisis event choice effects',
    confidence: 'judgement',
    title: 'Bank stress event — choice payouts',
    note: 'SVB-UK / Credit Suisse comparable: coordinated rescue costs ~£10–20bn upfront with -0.2–0.4pp bond-yield relief. Bail-in (BRRD-style) cheaper (~£4bn) but raises perceived sovereign risk slightly. Bloc effects: working-class resentful of bailouts, business resentful of bail-ins.',
  },
  event_general_strike: {
    parameter: 'generalStrike event choice effects',
    confidence: 'judgement',
    title: 'Cross-sector strike — choice payouts',
    note: 'TUC coordinated days of action (2022–23): ~£2bn cumulative settlement envelope. Refusing produces a growth drag of ~0.3pp (BCC estimates) and large bloc penalties. Calibrated to the 1979 Winter of Discontent and 2022–23 wave; magnitudes are designer-set within those reference points.',
  },
  event_care_crisis: {
    parameter: 'careCrisis event choice effects',
    confidence: 'judgement',
    title: 'Care provider collapse — choice payouts',
    note: 'Southern Cross (2011) and Four Seasons (2019) collapses: public takeover ~£3–5bn one-off; private rescue ~£1bn underwriting. Pensioner bloc reaction tracks Age UK polling on care-home anxiety.',
  },
  event_flood: {
    parameter: 'flood event choice effects',
    confidence: 'judgement',
    title: 'Severe flooding — choice payouts',
    note: '2007 and 2015–16 floods: combined recovery + Pitt Review defences ~£5–7bn. Patch-up-only ~£3bn. Northern bloc reaction reflects post-flood polling in affected regions.',
  },
  event_heatwave: {
    parameter: 'heatwave event choice effects',
    confidence: 'judgement',
    title: 'Heatwave — choice payouts',
    note: 'CCC heat-adaptation packages ~£3bn over a parliament. Public-information campaigns are de minimis (~£0.2bn) but draw youth scorn on climate.',
  },
  event_ally_crisis: {
    parameter: 'allyCrisis event choice effects',
    confidence: 'judgement',
    title: 'International crisis — choice payouts',
    note: 'Ukraine military + macro-fiscal envelope (£4–6bn pa) is the reference for "full support". Diplomatic-only is fiscally free but draws professional/middle-class scepticism.',
  },
  event_labour_shortage: {
    parameter: 'labourShortage event choice effects',
    confidence: 'judgement',
    title: 'Labour shortages — choice payouts',
    note: 'Seasonal Worker scheme and shortage-occupation list expansions (2022–24): growth effect +0.2pp on a £20bn-affected-sectors base. "Hold the line" produces shortage-driven supply effects estimated at -0.3pp growth (NIESR 2023). Business and northern (immigration-restrictive) bloc tensions are well-polled.',
  },
  event_investment_surge: {
    parameter: 'investmentSurge event choice effects',
    confidence: 'judgement',
    title: 'Foreign investment surge — choice payouts',
    note: 'Sovereign-wealth UK infra deals (e.g. NEOM-style EU pensions) at £40bn scale yield ~0.3pp growth (OBR / NIESR multiplier estimates). Bloc gains modelled on visibility of high-profile project wins (Hinkley, Sizewell C).',
  },
  event_export_boom: {
    parameter: 'exportBoom event choice effects',
    confidence: 'judgement',
    title: 'Export surge — choice payouts',
    note: 'Clean-tech export wins (2022–25 wind/EV) added ~0.1–0.2pp to growth in good quarters (ONS trade stats). Northern bloc benefit reflects manufacturing-region concentration.',
  },
  event_productivity_jump: {
    parameter: 'productivityJump event choice effects',
    confidence: 'judgement',
    title: 'Productivity surprise — choice payouts',
    note: 'ONS occasional surprise revisions of 1pp+ have lifted forward growth ~0.4pp (e.g. Blue Book 2023). Professional/business bloc gains reflect wage-pass-through expectations.',
  },
  event_tax_beats: {
    parameter: 'taxBeats event choice effects',
    confidence: 'judgement',
    title: 'Tax receipts beat — choice payouts',
    note: 'Compliance-led overperformance (HMRC tax-gap initiatives) has produced ~£3–5bn windfalls in recent years. Deficit-vs-services split is the canonical political tradeoff; bloc reactions calibrated to that framing.',
  },
  event_demographic_dividend: {
    parameter: 'demographicDividend event choice effects',
    confidence: 'judgement',
    title: 'Female participation surge — choice payouts',
    note: 'Resolution Foundation 2023: each 1pp rise in female participation adds ~0.15–0.25pp annual growth. Childcare-extension reaction reflects youth and working-class beneficiary polling.',
  },
  event_trade_deal: {
    parameter: 'tradeDeal event choice effects',
    confidence: 'judgement',
    title: 'Trade deal signed — choice payouts',
    note: 'Major FTAs (CPTPP, India, GCC) have OBR-estimated long-run growth boosts ~0.1–0.2pp. Business/professional bloc gains reflect headline confidence channel.',
  },

  // ===========================================================================
  // Reform capacity & social-care extension
  // ===========================================================================
  reform_capacity_judgement: {
    parameter: 'reformCapacity scaling',
    confidence: 'judgement',
    title: 'Reform capacity scaling',
    note: 'Reform capacity is a designer-set constraint reflecting that any government can only run a finite number of substantive reform programmes simultaneously: ministerial bandwidth, civil-service drafting capacity, parliamentary time, and stakeholder management are all bottlenecks. The baseline cap of 5 (at starting departmental spend) and per-reform loads of 1–8 are calibrated to make sequencing decisions matter, not estimated from primary research. The +30bn per slot scaling means growing the state (via spending) buys reform throughput, while the +2 bonus from completing Civil Service Rebuild reflects restored departmental capacity.',
  },
  statutory_no_upfront_judgement: {
    parameter: 'upfront cost = 0 for statutory/admin reforms',
    confidence: 'judgement',
    title: 'Statutory/admin reform absorbed within existing DEL',
    note: "Reforms that change tax law, employment law, or regulatory rules without standing up new capital programmes, headcount, or service expansion incur no separate upfront cash beyond the responsible department's existing operating budget. Drafting, parliamentary time, and minor enforcement scaffolding are de minimis at the £bn-scale resolution of this model. Effects of each policy (revenue gains, supply-side responses, distributional effects) remain attributed to their original reform-specific citations.",
  },
  social_care_systemic_extrapolated: {
    parameter: 'socialCareSystemic reform',
    value: 12,
    unit: '£bn pa ongoingCost',
    confidence: 'extrapolated',
    title: 'Systemic social care reform — free personal care, workforce uplift, NHS/LA integration',
    publisher: "King's Fund / Health Foundation / IFS (composite range)",
    year: 2024,
    url: 'https://www.kingsfund.org.uk/insight-and-analysis/data-and-charts/social-care-360',
    note: "Composite range from King's Fund, Health Foundation, and IFS estimates places comprehensive social care reform — free personal care plus workforce pay parity with the NHS plus LA grant integration — at roughly £8–14bn pa steady state in 2024 prices. Simulation £12bn pa picks the mid-upper end on the assumption of a reasonably ambitious settlement; £10bn upfront covers transition, training-place expansion, and IT integration. healthBoost +5 reflects fewer delayed transfers of care and earlier intervention. Bloc reactions (publicSector +10 in particular) reflect the workforce pay component. Prerequisite Dilnot Cap captures the staged-implementation reality: systemic reform builds on the cap framework rather than replacing it.",
  },
};

// Helper: given a citationId, return the entry or throw.
export function getCitation(id) {
  const c = CITATIONS[id];
  if (!c) throw new Error(`Unknown citationId: ${id}`);
  return c;
}

// Helper: confidence-summary aggregation for the About tab.
export function confidenceSummary() {
  const counts = { sourced: 0, extrapolated: 0, judgement: 0 };
  for (const c of Object.values(CITATIONS)) counts[c.confidence] = (counts[c.confidence] || 0) + 1;
  const total = Object.values(counts).reduce((a, b) => a + b, 0);
  return {
    counts,
    total,
    pct: {
      sourced: total ? counts.sourced / total : 0,
      extrapolated: total ? counts.extrapolated / total : 0,
      judgement: total ? counts.judgement / total : 0,
    },
  };
}
